version: '3.9'
services:
  postgres-10:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/
      VERIFICA_IMPORTAR: ${VERIFICA_IMPORTAR}
    env_file: .env  
    volumes:
      - "postgres_db_10:/var/lib/postgresql/data/" 
      - .docker/dev/supervisor:/etc/supervisor.d
      - ./importar:/docker/importar   
      - ./importados:/docker/importados/   
      - ./arquivos:/docker/  
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    restart: unless-stopped      

networks:
  default:
    external: true
    name: ansata_net
    
volumes:
  postgres_db_10:
    
  


      

